version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: taxopark
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    
  taxopark:
    depends_on:
      - db
    image: taxopark-angular
    build:
      context: .
    ports:
      - "8090:80"
      
volumes:
  dbdata: